# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba3258cf1cbd76f2ca964712e7e61e127f9e4ce560d4074355904cb9d413ebc7adb653abd6520619445b3f19d37516a9fd5bbf742daccc0aa5d27e4dd613afe1

test:
  secret_key_base: fdc057db7a35e8b8fc047c6ccfdef393aa8e2ce67effea0563a14dc0f799f9a1ae165cc08ba77de1dbe0b5d2ab8eb16633caca07b5868dbb7f4fe7e2b808afa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
